<a href="https://colab.research.google.com/github/MouseAndKeyboard/HuggingFace/blob/main/Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install transformers[sentencepiece]

     |████████████████████████████████| 2.5MB 5.4MB/s 
     |████████████████████████████████| 901kB 33.2MB/s 
     |████████████████████████████████| 3.3MB 27.0MB/s 
     |████████████████████████████████| 1.1MB 38.1MB/s 


In [4]:
import transformers
from transformers import pipeline

In [ ]:
classifier = pipeline("sentiment-analysis")
classifier("This is an absolutely astonishing piece of code, it's truly a miracle it works")

[{'label': 'POSITIVE', 'score': 0.9998770356178284}]

In [ ]:
classifier([
    "I've been waiting for a HuggingFace course my whole life.", 
    "I hate this so much!"
])

[{'label': 'POSITIVE', 'score': 0.9598048329353333},
 {'label': 'NEGATIVE', 'score': 0.9994558095932007}]

In [ ]:
classifier = pipeline("zero-shot-classification")
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

{'labels': ['education', 'business', 'politics'],
 'scores': [0.844597339630127, 0.11197540909051895, 0.043427303433418274],
 'sequence': 'This is a course about the Transformers library'}

In [ ]:
classifier(
    "The banks have been upset by recent policy decisions by the former prime minister",
    candidate_labels=["education", "politics", "business"],
)

{'labels': ['business', 'politics', 'education'],
 'scores': [0.91004878282547, 0.08504610508680344, 0.00490508833900094],
 'sequence': 'The banks have been upset by recent policy decisions by the former prime minister'}

In [ ]:
generator = pipeline("text-generation")
generator("\"Have you seen Hamilton the musical?\"", num_return_sequences=3, max_length=20)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': '"Have you seen Hamilton the musical?"\n\nThe man answered that it was the best song he'},
 {'generated_text': '"Have you seen Hamilton the musical?"\n\n"Of my family."\n\n"You need'},
 {'generated_text': '"Have you seen Hamilton the musical?"\n\n"Hmmm," replied Alice curiously.\n\n'}]

In [ ]:
generator = pipeline("text-generation", model="EleutherAI/gpt-neo-125M")
generator("The librarian hummed", num_return_sequences=1)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'The librarian hummed to himself, "I\'m not sure I can do this."\n\n'}]

In [ ]:
unmasker = pipeline("fill-mask")
unmasker("She quickly ducked under the <mask> to dodge the bullet.", top_k=2)

[{'score': 0.13888324797153473,
  'sequence': 'She quickly ducked under the rubble to dodge the bullet.',
  'token': 20814,
  'token_str': ' rubble'},
 {'score': 0.06825678795576096,
  'sequence': 'She quickly ducked under the covers to dodge the bullet.',
  'token': 4865,
  'token_str': ' covers'}]

In [ ]:
ner = pipeline("ner", grouped_entities=True)
ner("Alice held hands with Jack, she watched the other people on the Eiffel Tower.")

/usr/local/lib/python3.7/dist-packages/transformers/pipelines/token_classification.py:155: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="AggregationStrategy.SIMPLE"` instead.
  f'`grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="{aggregation_strategy}"` instead.'


[{'end': 5,
  'entity_group': 'PER',
  'score': 0.972418,
  'start': 0,
  'word': 'Alice'},
 {'end': 26,
  'entity_group': 'PER',
  'score': 0.9935928,
  'start': 22,
  'word': 'Jack'},
 {'end': 76,
  'entity_group': 'LOC',
  'score': 0.8946363,
  'start': 64,
  'word': 'Eiffel Tower'}]

In [ ]:
summarizer = pipeline("summarization")
summarizer("""
    America has changed dramatically during recent years. Not only has the number of 
    graduates in traditional engineering disciplines such as mechanical, civil, 
    electrical, chemical, and aeronautical engineering declined, but in most of 
    the premier American universities engineering curricula now concentrate on 
    and encourage largely the study of engineering science. As a result, there 
    are declining offerings in engineering subjects dealing with infrastructure, 
    the environment, and related issues, and greater concentration on high 
    technology subjects, largely supporting increasingly complex scientific 
    developments. While the latter is important, it should not be at the expense 
    of more traditional engineering.

    Rapidly developing economies such as China and India, as well as other 
    industrial countries in Europe and Asia, continue to encourage and advance 
    the teaching of engineering. Both China and India, respectively, graduate 
    six and eight times as many traditional engineers as does the United States. 
    Other industrial countries at minimum maintain their output, while America 
    suffers an increasingly serious decline in the number of engineering graduates 
    and a lack of well-educated engineers.
""")

[{'summary_text': ' America has changed dramatically during recent years . The number of engineering graduates in the U.S. has declined in traditional engineering disciplines such as mechanical, civil,    electrical, chemical, and aeronautical engineering . Rapidly developing economies such as China and India continue to encourage and advance the teaching of engineering .'}]

In [5]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [28]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.", 
    "I hate this so much!",
    "I really hate how fantastic this product is"
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  1045,  2428,  5223,  2129, 10392,  2023,  4031,  2003,   102,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])}


The attention mask is what the transformer is able to use
The input_ids are unique for each word/token.

In [7]:
from transformers import AutoModel
checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
model = AutoModel.from_pretrained(checkpoint)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['pre_classifier.bias', 'pre_classifier.weight', 'classifier.bias', 'classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [9]:
result = model(**inputs)

In [11]:
result.last_hidden_state.shape

torch.Size([2, 16, 768])

In [29]:
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [30]:
outputs = model(**inputs)

In [31]:
print(outputs.logits.shape)

torch.Size([3, 2])


In [32]:
import torch

In [33]:
torch.nn.functional.softmax(outputs.logits, dim=-1)  

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04],
        [9.7941e-01, 2.0587e-02]], grad_fn=<SoftmaxBackward>)

In [34]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

So the general pipeline is:


1.   Perform tokenisation
  1. For this we need to load the tokeniser, this will be different for each model
2.   Load a model
4.   Input tokenised inputs
3.   Interpret results
  1. We need to get the last hidden state and run softmax on that

In [49]:
tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english') # SST-2 is a binary classification benchmark
tokens = tokenizer(['the quick brown fox jumped over the lazy dog.', 'hello there happy young man'], truncation=True, padding=True, return_tensors='pt')
tokens

{'input_ids': tensor([[  101,  1996,  4248,  2829,  4419,  5598,  2058,  1996, 13971,  3899,
          1012,   102],
        [  101,  7592,  2045,  3407,  2402,  2158,   102,     0,     0,     0,
             0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])}

In [52]:
model = AutoModel.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')
result = model(**tokens)
result

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['pre_classifier.bias', 'pre_classifier.weight', 'classifier.bias', 'classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BaseModelOutput([('last_hidden_state',
                  tensor([[[-0.2509,  0.2118,  0.0959,  ..., -0.6876,  0.7087,  0.2533],
                           [-0.7647,  0.0893, -0.3439,  ..., -0.3623,  1.0587, -0.0668],
                           [-0.5846,  0.0328, -0.1139,  ..., -0.4984,  0.7292,  0.0574],
                           ...,
                           [-0.4013,  0.4138, -0.0623,  ..., -0.6888,  0.7589,  0.2181],
                           [ 0.3377,  0.1835,  0.0225,  ...,  0.1045,  0.2629, -0.3319],
                           [ 0.1429,  0.4212,  0.3817,  ...,  0.0452,  0.3816, -0.1198]],
                  
                          [[ 0.4363,  0.4781,  0.2589,  ...,  0.6698,  0.9638, -0.5023],
                           [ 0.6424,  0.6172,  0.4754,  ...,  0.4385,  0.9752, -0.5334],
                           [ 0.5446,  0.6055,  0.5542,  ...,  0.3254,  0.9752, -0.5919],
                           ...,
                           [ 0.2631,  0.4378,  0.4096,  ...,  0.7649,  0.898

In [56]:
result.last_hidden_state.shape

torch.Size([2, 12, 768])

In [65]:
classifier = AutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')
output = classifier(**tokens)

In [67]:
torch.nn.functional.softmax(output.logits, dim=-1)

tensor([[9.3007e-01, 6.9933e-02],
        [1.6149e-04, 9.9984e-01]], grad_fn=<SoftmaxBackward>)